const products=[
{id:1,name:"Jaket Gunung Outdoor",category:"Jaket",price:250000,rating:4.8,badge:"OUTDOOR",desc:"Jaket hardshell untuk hiking, trekking, dan camping.",image:"https://imageserver.graas.ai/services/uploads/IGZ/Shinmudra-IGZ1294450/s3/WKNA/90ec_dc3b81_original.jpg",fallback:"https://images.unsplash.com/photo-1551698618-1dfe5d97d256?auto=format&fit=crop&w=900&q=80"},
{id:2,name:"Sepatu Gunung Adventure",category:"Sepatu",price:350000,rating:4.7,badge:"HIKING",desc:"Sepatu hiking dengan grip agresif untuk jalur berbatu.",image:"https://jackwalker.co.uk/cdn/shop/files/1_2fa2e15e-23da-44b0-b115-7b7176285878.png?v=1761403109&width=533",fallback:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80"},
{id:3,name:"Tas Carrier 60L",category:"Tas",price:450000,rating:4.9,badge:"60 LITER",desc:"Carrier besar untuk perjalanan beberapa hari di gunung.",image:"https://ciengood.com/wp-content/uploads/2022/11/Waterproof-Hiking-Backpack-60L.jpg",fallback:"https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80"},
{id:4,name:"Tenda Camping 2 Orang",category:"Tenda",price:550000,rating:4.8,badge:"2 ORANG",desc:"Tenda dome ringkas untuk camping dan pendakian.",image:"https://www.campmor.com/cdn/shop/products/2000024586_1.jpg?v=1664278856",fallback:"https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=900&q=80"},
{id:5,name:"Sleeping Bag Outdoor",category:"Sleeping Bag",price:180000,rating:4.6,badge:"WARM",desc:"Sleeping bag hangat dan mudah dibawa dalam carrier.",image:"https://m.media-amazon.com/images/I/71XQ3r1QJFL._AC_SL1500_.jpg",fallback:"https://images.unsplash.com/photo-1526481280695-3c687fd643ed?auto=format&fit=crop&w=900&q=80"},
{id:6,name:"Headlamp LED Outdoor",category:"Outdoor",price:85000,rating:4.7,badge:"LED",desc:"Headlamp hands-free untuk aktivitas malam dan camping.",image:"https://cdn.manomano.com/images/images_products/30045240/P/138313274_1.jpg",fallback:"https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=900&q=80"}
];
let cart=JSON.parse(localStorage.getItem("gondrongCart")||"[]"),currentCategory="all";
const grid=document.getElementById("productGrid"),searchInput=document.getElementById("searchInput");
const rupiah=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
function renderProducts(){const q=searchInput.value.trim().toLowerCase();const filtered=products.filter(p=>(currentCategory==="all"||p.category===currentCategory)&&(!q||`${p.name} ${p.category} ${p.desc}`.toLowerCase().includes(q)));grid.innerHTML=filtered.length?filtered.map(p=>`<article class="product-card"><div class="product-image"><span class="product-badge">${p.badge}</span><img src="${p.image}" alt="${p.name}" loading="lazy" onerror="this.onerror=null;this.src='${p.fallback}'"></div><div class="product-body"><div class="product-cat">${p.category}</div><h3 class="product-name">${p.name}</h3><p class="product-desc">${p.desc}</p><div class="product-meta"><span class="price">${rupiah(p.price)}</span><span class="stars">★★★★★ ${p.rating}</span></div><button class="buy-btn" onclick="addToCart(${p.id})">+ TAMBAH KE KERANJANG</button></div></article>`).join(""):"<div class='empty-cart' style='grid-column:1/-1'>Produk yang dicari belum ditemukan.</div>"}
function saveCart(){localStorage.setItem("gondrongCart",JSON.stringify(cart));updateCart()}
function addToCart(id){const item=cart.find(x=>x.id===id);item?item.qty++:cart.push({id,qty:1});saveCart();openCart()}
function changeQty(id,d){const item=cart.find(x=>x.id===id);if(!item)return;item.qty+=d;if(item.qty<=0)cart=cart.filter(x=>x.id!==id);saveCart()}
function removeItem(id){cart=cart.filter(x=>x.id!==id);saveCart()}
function updateCart(){document.getElementById("cartCount").textContent=cart.reduce((s,x)=>s+x.qty,0);const box=document.getElementById("cartItems");if(!cart.length){box.innerHTML='<div class="empty-cart">Keranjang masih kosong.<br>Yuk pilih gear untuk petualanganmu.</div>';document.getElementById("cartTotal").textContent=rupiah(0);return}let total=0;box.innerHTML=cart.map(i=>{const p=products.find(x=>x.id===i.id),sub=p.price*i.qty;total+=sub;return `<div class="cart-item"><img src="${p.image}" alt="${p.name}" onerror="this.onerror=null;this.src='${p.fallback}'"><div><h4>${p.name}</h4><small>${rupiah(p.price)}</small><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><strong>${i.qty}</strong><button onclick="changeQty(${p.id},1)">+</button></div><button class="remove" onclick="removeItem(${p.id})">Hapus</button></div><strong>${rupiah(sub)}</strong></div>`}).join("");document.getElementById("cartTotal").textContent=rupiah(total)}
function openCart(){document.getElementById("cartPanel").classList.add("show");document.getElementById("cartBackdrop").classList.add("show")}
function closeCart(){document.getElementById("cartPanel").classList.remove("show");document.getElementById("cartBackdrop").classList.remove("show")}
document.getElementById("cartButton").onclick=openCart;document.getElementById("closeCart").onclick=closeCart;document.getElementById("cartBackdrop").onclick=closeCart;searchInput.oninput=renderProducts;
document.querySelectorAll(".category-card").forEach(b=>b.onclick=()=>{document.querySelectorAll(".category-card").forEach(x=>x.classList.remove("active"));b.classList.add("active");currentCategory=b.dataset.category;renderProducts();document.getElementById("produk").scrollIntoView({behavior:"smooth"})});
document.getElementById("promoButton").onclick=()=>{currentCategory="all";searchInput.value="";document.querySelectorAll(".category-card").forEach(x=>x.classList.toggle("active",x.dataset.category==="all"));renderProducts();document.getElementById("produk").scrollIntoView({behavior:"smooth"})};
document.getElementById("checkoutButton").onclick=()=>{if(!cart.length)return alert("Keranjang masih kosong.");let lines=["Halo Gondrong Store, saya ingin memesan:"];let total=0;cart.forEach(i=>{const p=products.find(x=>x.id===i.id),sub=p.price*i.qty;total+=sub;lines.push(`- ${p.name} x${i.qty} = ${rupiah(sub)}`)});lines.push(`Total: ${rupiah(total)}`);lines.push("Mohon info ketersediaan dan proses pesanannya.");window.open(`https://wa.me/6287821939022?text=${encodeURIComponent(lines.join("\n"))}`,"_blank")};
renderProducts();updateCart();
